import turtle
shelly=turtle.Turtle()
shelly.shape('turtle')
shelly.color('red')
shelly.left(60)
shelly.backward(100)
shelly.circle(30)
shelly.circle(20)
shelly.circle(10)
shelly.penup()
shelly.backward(100)
shelly.left(90)
shelly.pendown()
shelly.forward(100)
shelly.reset()
shelly.goto(35,80)
shelly.hideturtle()

turtle.done()