/*分數群組判斷*/ 
#include <stdio.h>
#include <stdlib.h>

int main()
{
	char ch;/*宣告ch字元變數*/
	
	printf("A~Z\n");
	printf("請輸入分數群組:");
	
	scanf("%c",&ch);/*輸入字元變數ch*/
	/*switch 條件敘述開始*/
	switch(ch)
	{
		/*此處不佳大括號*/
		case'A':
		case'a':/*輸入大寫或小寫字母都可*/
			printf("Agree!\n");
			break;
		case'B':
		case'b':/*輸入大寫或小寫字母都可*/
			printf("Bedroom!\n");
			break;
		case'C':
		case'c':/*輸入大寫或小寫字母都可*/
			printf("Center!\n");
			break;
		case'D':
		case'd':/*輸入大寫或小寫字母都可*/
			printf("December!\n");
			break;
		case'E':
		case'e':/*輸入大寫或小寫字母都可*/
			printf("Engineer!\n");
			break;
		case'F':
		case'f':/*輸入大寫或小寫字母都可*/
			printf("Fireworks!\n");
			break;
		case'G':
		case'g':/*輸入大寫或小寫字母都可*/
			printf("Goodbye!\n");
			break;
		case'H':
		case'h':/*輸入大寫或小寫字母都可*/
			printf("Health!\n");
			break;
		case'I':
		case'i':/*輸入大寫或小寫字母都可*/
			printf("Important!\n");
			break;
		case'J':
		case'j':/*輸入大寫或小寫字母都可*/
			printf("January!\n");
			break;
		case'K':
		case'k':/*輸入大寫或小寫字母都可*/
			printf("Knowledge!\n");
			break;
		case'L':
		case'l':/*輸入大寫或小寫字母都可*/
			printf("Language!\n");
			break;
		case'M':
		case'm':/*輸入大寫或小寫字母都可*/
			printf("Mailman!\n");
			break;
		case'N':
		case'n':/*輸入大寫或小寫字母都可*/
			printf("Neighbor!\n");
			break;
		case'O':
		case'o':/*輸入大寫或小寫字母都可*/
			printf("Outside!\n");
			break;
		case'P':
		case'p':/*輸入大寫或小寫字母都可*/
			printf("Papaya!\n");
			break;
		case'Q':
		case'q':/*輸入大寫或小寫字母都可*/
			printf("Queen!\n");
			break;
		case'R':
		case'r':/*輸入大寫或小寫字母都可*/
			printf("Rabbit!\n");
			break;
		case'S':
		case's':/*輸入大寫或小寫字母都可*/
			printf("Sandwich!\n");
			break;
		case'T':
		case't':/*輸入大寫或小寫字母都可*/
			printf("Teenager!\n");
			break;
		case'U':
		case'u':/*輸入大寫或小寫字母都可*/
			printf("Uniform!\n");
			break;
		case'V':
		case'v':/*輸入大寫或小寫字母都可*/
			printf("Voice!\n");
			break;
		case'W':
		case'w':/*輸入大寫或小寫字母都可*/
			printf("Watermelon!\n");
			break;
		case'X':
		case'x':/*輸入大寫或小寫字母都可*/
			printf("Xylophone!\n");
			break;
		case'Y':
		case'y':/*輸入大寫或小寫字母都可*/
			printf("Yummy!\n");
			break;
		case'Z':
		case'z':/*輸入大寫或小寫字母都可*/
			printf("Zebra!\n");
			break;
		default:/*其他字元則執行default指令*/
			printf("沒有此分數群組\n");
			break;					
	}  
	
	return 0;
}
