a=int( input("請輸入姓名:"))
b=int( input("請輸入第一天的零用錢:"))
c=int( input("請輸入第二天的零用錢:"))
d=int( input("請輸入第三天的零用錢:"))
e=int( input("請輸入第四天的零用錢:"))
f=int( input("請輸入第五天的零用錢:"))
g=int( input("請輸入第六天的零用錢:"))
h=int( input("請輸入第七天的零用錢:"))
print("name","day1","day2","day3","day4","day5","day6","day7")
print("{0:1}{1:5}{2:5}{3:5}{4:5}{5:5}{6:5}{7:5}".format(a,b,c,d,e,f,g,h))